require 'rlayout'
require 'debug'

task :default => [:generate_pdf]


desc 'create new issue'
task :new_issue do
  publication_path = File.dirname(__FILE__)
  date = Date.today.to_s
  issue_path  = publication_path + "/#{date}"
  RLayout::NewsIssuePlan.new(issue_path)
end

desc 'update issue'
task :update do
  publication_path = File.dirname(__FILE__)
  date = Date.today.to_s
  issue_path  = publication_path + "/#{date}"
  RLayout::NewsIssuePlan.update(issue_path)
end

desc 'generate book pdf'
task :print_order do
  project_path = File.dirname(__FILE__)
  index_path = project_path +  "/index.html"
  system "open #{index_path}"

  # open webpage of ????
  # TODO
  # price quote for current book
  # start payment process
  # process payment
  # if payment is done
  #   copy print file to printer server
  #   assign job_id
  #   track the job process,
  #   delivery status
  #   in person confirmation call?
end