
require 'rlayout'
# require 'pry'
task :default => [:hwpx2md_processor]

desc 'generate book pdf'
task :hwpx2md_processor do
  project_path = File.dirname(__FILE__)
  RLayout::Hwpx2mdProcessor.new(project_path)
end
