
require 'rlayout'
# require 'pry'
task :default => [:txt2md_processor]

desc 'generate book pdf'
task :txt2md_processor do
  project_path = File.dirname(__FILE__)
  RLayout::Txt2mdProcessor.new(project_path)
end
